# Generated by Django 4.2.20 on 2025-04-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('payment_time', models.DateTimeField(verbose_name='payment time')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
