# Generated by Django 4.2.20 on 2025-04-15 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='money',
            old_name='username',
            new_name='name',
        ),
    ]
