# Generated by Django 4.2.20 on 2025-04-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_rename_username_money_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='money',
            field=models.DecimalField(decimal_places=2, default=750, max_digits=10),
        ),
    ]
