# Generated by Django 4.2.20 on 2025-04-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='converted_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
