# Generated by Django 4.2.20 on 2025-04-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='currency',
            field=models.CharField(choices=[('GBP', 'British Pound Sterling'), ('EUR', 'Euro'), ('USD', 'US Dollars')], default='GBP', max_length=3),
            preserve_default=False,
        ),
    ]
