# Generated by Django 4.2.20 on 2025-04-15 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Payment',
        ),
    ]
