# Generated by Django 4.2.20 on 2025-04-16 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_rename_comment_payment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='Request',
        ),
    ]
