# Generated by Django 4.2.20 on 2025-04-16 06:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_rename_payment_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='payment_amount',
            new_name='request_amount',
        ),
        migrations.RemoveField(
            model_name='request',
            name='payment_time',
        ),
        migrations.AddField(
            model_name='request',
            name='request_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='request time'),
        ),
    ]
