# Generated by Django 4.2.20 on 2025-04-16 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0005_request_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='user',
        ),
    ]
